//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_Editor_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XML_Editor_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Dist - параметр отвечающий за радиус действия оружия.
        ///Используется для Миномётов и некоторого навесного оружия..
        /// </summary>
        public static string ActionDistDescription {
            get {
                return ResourceManager.GetString("ActionDistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string AddNewBTN {
            get {
                return ResourceManager.GetString("AddNewBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast Wave Prototype - тип взрывной волны, которую вызывает попадание по объекту.
        ///Может прописываться как оружию, снаряду, машине противника при взрыве.
        ///
        ///Существующие значения:
        /// - smallBlastWave - используется для оружия (Флаг, Рапира, Циклоп и т.д.).
        /// - bossMetalArmLoadBlastWave0 (bossMetalArmLoadBlastWave1, bossMetalArmLoadBlastWave2) - взрывная волна от снаряда Босса (оба крана).
        /// - boss03rocketBlastWave (boss03CrocketBlastWave) - взрывная волна от ракеты Босса (Оракула).
        /// - someBlastWaveRocket01  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlastWavePrototypeDescription {
            get {
                return ResourceManager.GetString("BlastWavePrototypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прототип снаряда.
        /// </summary>
        public static string BulletPrototype {
            get {
                return ResourceManager.GetString("BulletPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Prototype - Прототип снаряда. 
        ///
        ///В игре есть несколько типов снаряда:
        /// - raybullet - огнестрельное оружие.
        /// - someMortarShell (someMortarShell02) - гранаты миномёта.
        /// - someLaserBeamGreen (someLaserBeamBlue) - лазерное оружие.
        /// - somePlasmaBunch (somePlasmaBunchBig) - сгустки плазмы.
        /// - hurricane_rocket (rocket_sml01, dragon_rocket, и т.д.) - ракеты для ракетниц.
        /// Все прототипы снаряда содержатся в файле: &quot;\data\gamedata\gameobjects\ammunition.xml&quot;
        /// 
        /// Можно создавать свои прототипы, указыват [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BulletPrototypeDescription {
            get {
                return ResourceManager.GetString("BulletPrototypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Be Dropped From Enemies	- Выпадает из врагов?
        ///Да\Нет = &quot;1&quot;\&quot;0&quot; (Без кавычек)..
        /// </summary>
        public static string CanBeDroppedFromEnemiesDescription {
            get {
                return ResourceManager.GetString("CanBeDroppedFromEnemiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can BeUsed In Autogenerating - Может ли оружие быть использовано для автоматической генерации.
        ///Запрещает использовать оружие при автогенерации врагов (для InfectionZone команд к примеру).
        ///Флаг 1\0 = да\нет. .
        /// </summary>
        public static string CanBeUsedInAutogeneratingDescription {
            get {
                return ResourceManager.GetString("CanBeUsedInAutogeneratingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string CancelBTN {
            get {
                return ResourceManager.GetString("CancelBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Size - Размер активной обоймы.
        ///То есть сколько выстрелов будет произведено до начала перезарядки..
        /// </summary>
        public static string ChargeSizeDescription {
            get {
                return ResourceManager.GetString("ChargeSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class -  Класс оружия, из которого определяется вид выстрела(прототип) и многое другое.
        ///Все названия красноречивы и легки для понимания, если перевести с английского на русский.
        ///
        ///Перечень возможных вариантов (возможно не полный):
        /// - BulletLauncher - Огнестрельное (стреляет пулями или снарядами по прямой траектории).
        /// - Mortar - Миномёт (снаряд летит по навесной траектории).
        /// - PlasmaBunchLauncher - Лазерное и плазменное оружие (характерны низкая скорость полёта снаряда).
        /// - RocketLauncher - Ракетная  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClassDescription {
            get {
                return ResourceManager.GetString("ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEM team © 27.03.2014.
        /// </summary>
        public static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урон.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage - Повреждения от 1го снаряда..
        /// </summary>
        public static string DamageDescription {
            get {
                return ResourceManager.GetString("DamageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Type - Тип повреждения. В игре очень мало используется.
        ///
        ///Существуют такие значения:
        /// - BLAST - взрыв.
        /// Остальные значения неизвестны. Если не устанавливать - ставится 
        /// некое значение по умолчанию..
        /// </summary>
        public static string DamageTypeDescription {
            get {
                return ResourceManager.GetString("DamageTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decal - Тип накладываемого изображения на автомобиль после попадания в него из данного оружия.
        ///
        ///Существуют в игре такие типы:
        /// - DC_SML_MACHINEGUN - Пулемёты и дробовики небольшого калибра.
        /// - DC_BIG_MACHINEGUN - Пулемёты и дробовики большого калибра.
        /// - DC_GUN - Пушки.
        /// - DC_LASER - Лазеры и плазма.
        /// - DC_ROKET - Ракеты.
        ///
        /// Теоретически есть возможность добавлять свои Декали. 
        /// На практике пока не проверено..
        /// </summary>
        public static string DecalDescription {
            get {
                return ResourceManager.GetString("DecalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалять без подтверждения.
        /// </summary>
        public static string DELETE_CHEKER {
            get {
                return ResourceManager.GetString("DELETE_CHEKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteBTN {
            get {
                return ResourceManager.GetString("DeleteBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeusExMachina.
        /// </summary>
        public static string DEM_URL {
            get {
                return ResourceManager.GetString("DEM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durability - прочность оружия.
        ///При падении показателя прочности до 0 - оружие выходит из строя..
        /// </summary>
        public static string DurabilityDescription {
            get {
                return ResourceManager.GetString("DurabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string EditBTN {
            get {
                return ResourceManager.GetString("EditBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эфект попадания.
        /// </summary>
        public static string ExplosionType {
            get {
                return ResourceManager.GetString("ExplosionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion Type - Тип эффекта от попадания.
        ///
        ///В игре есть такие типы:
        /// - MACHINEGUN - Пулемет.
        /// - AUTOCANNON - Пулемёт крупного калибра.
        /// - GRENADE - Миномёт.
        /// - CANNON - Пушка.
        /// - LASER - Лазер.
        /// - PLASMA - Плазма.
        /// - BLAST - Ракета.
        ///
        /// Меридиан 113:
        /// - FLAME - Огнемёт..
        /// </summary>
        public static string ExplosionTypeDescription {
            get {
                return ResourceManager.GetString("ExplosionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес файла:.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Effect - Эффект от выстрела. У всех по умолчанию &quot;none&quot;.
        ///У ракетниц изначально не прописан вовсе. Вероятно в этом случае 
        ///движок игры по умолчанию так же выставляет &quot;none&quot;..
        /// </summary>
        public static string FiringEffectDescription {
            get {
                return ResourceManager.GetString("FiringEffectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Range - Дальность стрельбы.
        ///Дальше этого порога урон не наносится,
        ///или уменьшается по формуле до 0..
        /// </summary>
        public static string FiringRangeDescription {
            get {
                return ResourceManager.GetString("FiringRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорострельность.
        /// </summary>
        public static string FiringRate {
            get {
                return ResourceManager.GetString("FiringRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Rate - Скорострельность оружия (к примеру: 600 выстрелов в минуту)..
        /// </summary>
        public static string FiringRateDescription {
            get {
                return ResourceManager.GetString("FiringRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип выстрела (оружия).
        /// </summary>
        public static string FiringType {
            get {
                return ResourceManager.GetString("FiringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing Type - Тип выстрела (оружия).
        ///Существуют такие параметры:
        /// - MachineGun - Пулемет.
        /// - Laser - Лазер.
        /// - ShotGun - Дробовик.
        /// - Plasma - Плазма.
        /// - Artillery - Миномёт.
        /// - Cannon - Пушка.
        /// - Rocket - Ракетница.
        ///
        /// Меридиан 113:
        ///  - FlamePlasma - Огнемёт.
        ///  - ElectroPlasma - Авто-стоп (Шокер)..
        /// </summary>
        public static string FiringTypeDescription {
            get {
                return ResourceManager.GetString("FiringTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Angle - разброс пуль при стрельбе.
        ///Чем выше значение - тем больше разброс..
        /// </summary>
        public static string GroupingAngleDescription {
            get {
                return ResourceManager.GetString("GroupingAngleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Velocity - параметр отвечающий за первоначальную скорость снаряда.
        ///Регулирует скорость полёта снаряда у Миномёта..
        /// </summary>
        public static string InitialVelocityDescription {
            get {
                return ResourceManager.GetString("InitialVelocityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить файл.
        /// </summary>
        public static string LoadFileBTN {
            get {
                return ResourceManager.GetString("LoadFileBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass - Масса оружия установленного на автомобиле.
        ///Параметр вероятно рабочий, но не используется в игре.
        ///У всего оружия выставлен вес в 1.0. .
        /// </summary>
        public static string MassDescription {
            get {
                return ResourceManager.GetString("MassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Charges - применение параметра неизвестно.
        ///Возможно он вообще не активен.
        ///
        ///Встречается на таком оружии: hunterLauncher и rocketLauncher..
        /// </summary>
        public static string MaxChargesDescription {
            get {
                return ResourceManager.GetString("MaxChargesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model File - Имя отображаемой модели.
        ///
        ///Все модели в игре прописаны в файле: &quot;\data\models\animmodels.xml&quot;.
        ///
        ///Имена моделей доступные на локации: &quot;\data\maps\r1m1\servers.xml&quot;, 
        ///где r1m1 - имя локации (в данном случае это Край).
        ///
        ///Если модель есть в &quot;animmodels.xml&quot;, но её нет в &quot;servers.xml&quot; 
        ///нужной вам карты - можете прописать её в &quot;servers.xml&quot; вручную..
        /// </summary>
        public static string ModelFileDescription {
            get {
                return ResourceManager.GetString("ModelFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name - используется в качестве ID оружия,
        ///по которому определяется в связанных файлах.
        ///
        ///Например &quot;modelicons.xml&quot; или &quot;model_names.xml&quot;..
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Scale - Параметр управляющий размером модели по осям.
        ///К сожалению отключен или не работает.
        ///Изменения данного параметра ожидаемого результата не дают..
        /// </summary>
        public static string NodeScaleDescription {
            get {
                return ResourceManager.GetString("NodeScaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Bullets In Shot - Количество пуль в выстреле.
        ///Обязательный параметр для дробовика.
        ///Каждая пуля наносит урон заданный в параметре Damage..
        /// </summary>
        public static string NumBulletsInShotDescription {
            get {
                return ResourceManager.GetString("NumBulletsInShotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпросмотр:.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price - Цена на оружие.
        ///В магазине продаётся по указанной стоимости..
        /// </summary>
        public static string PriceDescription {
            get {
                return ResourceManager.GetString("PriceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт программы.
        /// </summary>
        public static string PROGRAM_URL {
            get {
                return ResourceManager.GetString("PROGRAM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharging Time - Время перезарядки оружия в секундах..
        /// </summary>
        public static string RechargingTimeDescription {
            get {
                return ResourceManager.GetString("RechargingTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Force - Сила отдачи.
        ///Чем выше число -сильнее отдача..
        /// </summary>
        public static string RecoilForceDescription {
            get {
                return ResourceManager.GetString("RecoilForceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип слота.
        /// </summary>
        public static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type - параметр, в котором задаётся тип слота, 
        ///на который будет устанавливаться оружие.
        ///
        ///Стандартные слоты игровых моделей:
        /// - SMALL_GUN - Маленькое оружие. Размер слота 2х2.
        /// - BIG_GUN - Большое оружие. Размер слота 2х3.
        /// - GIANT_GUN - Гигантское оружие. Размер слота 3х4.
        ///
        /// Стандартные слоты игровых моделей,
        /// которые не используются в данной версии программы:
        ///  - SIDE_GUN - Оружие навесное в специальные слоты по бокам кузова(кабины).
        ///  Составное, состоит из 2х половинок. Размер слота 3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResourceTypeDescription {
            get {
                return ResourceManager.GetString("ResourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveBTN {
            get {
                return ResourceManager.GetString("SaveBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл.
        /// </summary>
        public static string SelectFileBTN {
            get {
                return ResourceManager.GetString("SelectFileBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shells Pool Size - Параметр необходим для указания количества снарядов для данного оружия.
        ///Используется только для вооружения с огранченым запасом вооружения.
        ///
        ///Важно!
        ///Обязательное условие: &quot;With Shells Pool Limit&quot; должен быть выставлен в &quot;true&quot;..
        /// </summary>
        public static string ShellsPoolSizeDescription {
            get {
                return ResourceManager.GetString("ShellsPoolSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeaponXmlEditor - Окно редактирования.
        /// </summary>
        public static string Title_AddWindow {
            get {
                return ResourceManager.GetString("Title_AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeaponXmlEditor - Главное окно.
        /// </summary>
        public static string Title_MainWindow {
            get {
                return ResourceManager.GetString("Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracer Effect - След(эффект) от выстрела.
        ///В игре виден как вспышка и трассер летящего снаряда.
        ///Просмотреть прописанные в игру варианты возможно при 
        ///помощи утилиты GSMED. Скачать можно на сайте DeusExMachina.fsay.net.
        /// </summary>
        public static string TracerEffectDescription {
            get {
                return ResourceManager.GetString("TracerEffectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracer Range - параметр отвечающий за расстояние возникновения 
        ///следа(эффекта) от выстрела от конца ствола оружия..
        /// </summary>
        public static string TracerRangeDescription {
            get {
                return ResourceManager.GetString("TracerRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning Speed - скорость поворота оружия.
        ///По умолчанию отсутствует у всех, кроме Миномётов и Пушки танка.
        ///.
        /// </summary>
        public static string TurningSpeedDescription {
            get {
                return ResourceManager.GetString("TurningSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible In Encyclopedia - Разрешено для показа в Энциклопедии.
        ///Да/Нет - &quot;true&quot;/&quot;false&quot; (Без кавычек)..
        /// </summary>
        public static string VisibleInEncyclopediaDescription {
            get {
                return ResourceManager.GetString("VisibleInEncyclopediaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Shells Pool Limit - параметр указывает на то,
        ///являются ли боеприпасы у оружия бесконечными или нет.
        ///&quot;false&quot; или пустая графа - бесконечны.
        ///&quot;true&quot; - заканчиваются.
        ///
        ///Важно!
        ///При установке параметра в &quot;true&quot;, параметр &quot;Shells Pool Size&quot; должен быть заполнен..
        /// </summary>
        public static string WithShellsPoolLimitDescription {
            get {
                return ResourceManager.GetString("WithShellsPoolLimitDescription", resourceCulture);
            }
        }
    }
}
